[2024-11-25T16:26:16.485+0900] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-25T16:26:16.496+0900] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_and_upload_json_to_hdfs.process_json_files scheduled__2024-11-25T06:00:00+00:00 [queued]>
[2024-11-25T16:26:16.503+0900] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_and_upload_json_to_hdfs.process_json_files scheduled__2024-11-25T06:00:00+00:00 [queued]>
[2024-11-25T16:26:16.503+0900] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-25T16:26:16.518+0900] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_json_files> on 2024-11-25 06:00:00+00:00
[2024-11-25T16:26:16.520+0900] {standard_task_runner.py:72} INFO - Started process 2699340 to run task
[2024-11-25T16:26:16.524+0900] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'process_and_upload_json_to_hdfs', 'process_json_files', 'scheduled__2024-11-25T06:00:00+00:00', '--job-id', '245', '--raw', '--subdir', 'DAGS_FOLDER/data_to_hdfs.py', '--cfg-path', '/tmp/tmpbz1dz7rs']
[2024-11-25T16:26:16.525+0900] {standard_task_runner.py:105} INFO - Job 245: Subtask process_json_files
[2024-11-25T16:26:16.562+0900] {task_command.py:467} INFO - Running <TaskInstance: process_and_upload_json_to_hdfs.process_json_files scheduled__2024-11-25T06:00:00+00:00 [running]> on host MN
[2024-11-25T16:26:16.623+0900] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='process_and_upload_json_to_hdfs' AIRFLOW_CTX_TASK_ID='process_json_files' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T06:00:00+00:00'
[2024-11-25T16:26:16.623+0900] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-25T16:26:31.036+0900] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/laewon/airflow_test/dags/data_to_hdfs.py", line 79, in read_and_process_json
    final_df.to_csv(output_csv, index=False)  # CSV 파일로 저장
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/pandas/core/generic.py", line 3772, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1186, in to_csv
    csv_formatter.save()
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 240, in save
    with get_handle(
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/pandas/io/common.py", line 737, in get_handle
    check_parent_directory(str(handle))
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/pandas/io/common.py", line 600, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/laewon/Riot/output'
[2024-11-25T16:26:31.044+0900] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=process_and_upload_json_to_hdfs, task_id=process_json_files, run_id=scheduled__2024-11-25T06:00:00+00:00, execution_date=20241125T060000, start_date=20241125T072616, end_date=20241125T072631
[2024-11-25T16:26:31.062+0900] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-25T16:26:31.062+0900] {standard_task_runner.py:124} ERROR - Failed to execute job 245 for task process_json_files (Cannot save file into a non-existent directory: '/laewon/Riot/output'; 2699340)
Traceback (most recent call last):
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/laewon/airflow_test/dags/data_to_hdfs.py", line 79, in read_and_process_json
    final_df.to_csv(output_csv, index=False)  # CSV 파일로 저장
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/pandas/core/generic.py", line 3772, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1186, in to_csv
    csv_formatter.save()
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 240, in save
    with get_handle(
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/pandas/io/common.py", line 737, in get_handle
    check_parent_directory(str(handle))
  File "/laewon/airflow_test/py_venv/lib/python3.8/site-packages/pandas/io/common.py", line 600, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/laewon/Riot/output'
[2024-11-25T16:26:31.076+0900] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-25T16:26:31.090+0900] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T16:26:31.090+0900] {local_task_job_runner.py:245} INFO - ::endgroup::
